name: Build/release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-14
            artifact_name: mac-arm64
            arch: arm64
            build_script: build:mac
          - os: macos-14
            artifact_name: mac-x64
            arch: x64
            build_script: build:mac-x64
          - os: windows-2022
            artifact_name: win-x64
            arch: x64
            build_script: build:win

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
        run: pnpm --filter @golive/desktop ${{ matrix.build_script }}
        env:
          ELECTRON_ARCH: ${{ matrix.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}-build
          path: |
            apps/desktop/dist/**/*.dmg
            apps/desktop/dist/**/GoLive*.exe
            apps/desktop/dist/**/*.blockmap
            apps/desktop/dist/**/latest*.yml

  release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            artifacts/**/*.dmg
            artifacts/**/GoLive*.exe
            artifacts/**/*.blockmap
            artifacts/mac-arm64-build/**/latest*.yml